trigger:
- sairam

resources:
- repo: self

variables:
  dockerRegistryServiceConnection: '4df82619-117a-4dee-a822-fd1c8f1342c3'
  imageRepository: 'saiirammmgamingproject'
  containerRegistry: 'sairamusa.azurecr.io'
  dockerfilePath: './'  # Make sure the Dockerfile is at the root
  tag: '$(Build.BuildId)-$(Build.SourceVersion)'  # Optional: More versioning
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push Docker image
  jobs:
  - job: Build
    displayName: Build Docker image
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push Docker image to registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

- stage: MavenBuild
  displayName: Maven Build
  jobs:
  - job: mavenBuild
    displayName: Run Maven Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Maven@4
      displayName: Build with Maven
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'clean install package'
        publishJUnitResults: true
        testResultsFiles: '**/target/*.xml'  # Adjust to the actual location of test reports
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false  # Set to true if you want to run SonarQube analysis
