apiVersion: apps/v1
kind: Deployment
metadata:
  name: sairam-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sairam-app
  template:
    metadata:
      labels:
        app: sairam-app
    spec:
      containers:
      - name: sairam-container
        image: tryimage.azurecr.io/newimage:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: tryimage00e2-auth
