apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - name: myapp
        image: sairamusa.azurecr.io/project:9
        ports:
        - containerPort: 8080
